src/gc-arena-derive/src/lib.rs
src/gc-arena/Cargo.toml
src/gc-arena/src/no_drop.rs
src/gc-arena/tests/tests.rs
src/gc-arena/tests/ui/invalid_collect_field.rs
src/gc-arena/tests/ui/invalid_collect_field.stderr
src/gc-arena/tests/ui/multiple_require_static.rs
src/gc-arena/tests/ui/multiple_require_static.stderr
src/gc-arena/tests/ui/no_drop_and_drop_impl.rs
src/gc-arena/tests/ui/no_drop_and_drop_impl.stderr
src/gc-arena/tests/ui/require_static_enum_variant.rs
src/gc-arena/tests/ui/require_static_enum_variant.stderr
src/gc-arena/tests/ui/require_static_not_static.rs
src/gc-arena/tests/ui/require_static_not_static.stderr

Currently, `#[collect(require_static)]` can be used on an entire
struct/enum. This commit allows `#[collect(require_static)]` to be
applied to individual fields or field bindings of a struct/enum.
When applied, we generate a where-clause bound ensuring that the type of
the field binding outlives 'static. This allows us to ignore the field
in `needs_trace` and `trace`.
As a result, it's now possible to use `#[derive(Collect)]` on a
struct/enum containing foreign types, as long as those foreign types are
'static.

  Allow using `#[collect(require_static)]` on fields 

---

src/gc-arena/Cargo.toml
src/gc-arena/src/no_drop.rs
src/gc-arena/tests/tests.rs
src/gc-arena/tests/ui/no_drop_and_drop_impl.rs
src/gc-arena/tests/ui/no_drop_and_drop_impl.stderr

The soundness of the code generated by `gc-arena-derive` relies on
certain things *not* compiling. Currently, this is not testing, making
it possible to accidentally introduce unsoundess.
This commit uses the `trybuild` crate to add compile-fail tests. To
start out, I've added a single test that verifies that
`#[collect(no_drop)]` causes a compilation error if a `Drop` impl is
present.

Use `trybuild` to test errors generated by gc-arena-derive

---

src/gc-arena/src/gc_cell.rs

Before:
```
Error message: panicked at 'already borrowed: BorrowMutError', gc-arena-0.2.0/src/gc_cell.rs:62:29
```
After: it shows the line that actually tried calling read()/write().
```
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm1/activation.rs:1186:48
```
Should help a bit with pinpointing error sources for library users :)

Add #[track_caller] for better panic error messages

---

src/gc-arena-derive/src/lib.rs
src/gc-arena/tests/ui/bad_collect_bound.rs
src/gc-arena/tests/ui/bad_collect_bound.stderr

We now span calls to `Collect::needs_trace` and `Collect::trace`
with the span of the field that we're generating the call for. This
leads to nicer error messages when a trait bound is not fulfulled (and
likely better runtime backtraces as well)

Use `quote_spanned` when generating calls to `gc_arena` methods

---

src/gc-arena/src/collect_impl.rs

This makes it easier to use `#[derive(Collect)]` on a struct containing
this type.

Add `Collect` impl for `PhantomData`

---

src/gc-arena-derive/Cargo.toml
src/gc-arena-derive/src/lib.rs
src/gc-arena/tests/ui/bad_collect_bound.stderr

PR #12 used `quote_spanned` to make error messages have the span of the
corresponding field in the struct. However, there's no indication that
the error comes from `#[derive(Collect)]`, which could be confusing for
people unfamiliar with the crate.
This PR uses `Span::resolved_at` to give the generated spans the hygiene
information from the call site. This causes rustc to add a note about
the error message originating from a macro, while still keeping the
error message at the proper location.

Use hygiene from `Span::call_site()` to produce error messages

---

src/gc-arena/src/context.rs
src/gc-arena/tests/ui/bad_collect_bound.stderr
src/gc-arena/tests/ui/no_drop_and_drop_impl.stderr
src/gc-arena/tests/ui/require_static_not_static.stderr

The error messages have changed, but the UI tests still correctly fail.

Update UI tests to match latest Rust output

---

src/gc-arena/src/context.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/gc_cell.rs
src/gc-arena/src/gc_weak.rs
src/gc-arena/src/gc_weak_cell.rs
src/gc-arena/src/lib.rs
src/gc-arena/src/types.rs
src/gc-arena/tests/tests.rs
src/gc-arena/tests/ui/bad_collect_bound.stderr

This is a combination of work by EmperorBale and me. It adds weak-pointer version of `Gc` and `GcCell`, named `GcWeak` and `GcWeakCell` respectively. These can be created by calling `downgrade()` on the corresponding 'strong' struct (`Gc`/`GcCell`).
You can attempt to upgrade a weak pointer to a strong pointer by calling `upgrade`. This will succeed as long as the target object has not yet been freed (it will also fail during `Phase::Sweep` when the target object is going to be freed, but has not yet been freed).
To support this, `GcBox` now has two additional flags: `alive` and `has_weak_ref`. When an allocation with weak pointers is garbage-collected, we just run the destructor on the `Collect` value if there are still weak pointers. The `GcBox` itself is not deallocated, so that the …

Add weak pointers `GcWeak` and `GcWeakCell`

---

src/gc-arena/src/arena.rs
src/gc-arena/src/context.rs
src/gc-arena/src/lib.rs

Surprisingly, this doesn't require GATs, and is actually simpler than a GAT-based solution. The core idea is to define a trait:
```rust
pub trait RootProvider<'a> {
type Root: Collect;
}
```
In `Arena`, we use the higher-ranked trait bound
`R: for<'a> RootProvider<'a>`. Then, writing
`<R as RootProvider<'gc>>::Root` gives us the root type with some arbitrary lifetime `'gc` substituted.
The `make_arena` macro can then simply declare the type alias `type MyArenaName = Arena<dyn for<'a> RootProvider<'a, Root = UserRoot<'a>>>`
Since a `RootProvider` trait object implements `RootProvider`, the projection `<R as RootProvider<'gc>>::Root` will evaluate to `UserRoot<'gc>`, without the need to define any additional structs or trait impls.

Define a single `Arena` struct and generate a type alias in `make_arena`

---

src/gc-arena/src/context.rs
src/gc-arena/src/types.rs

This leads to better codegen. See https://github.com/ruffle-rs/gc-arena/pull/7 for a more detailed discussion

Inline and microoptimize core functions

---

src/gc-arena-derive/src/lib.rs
src/gc-arena/src/collect.rs
src/gc-sequence/src/and_then.rs
src/gc-sequence/src/map.rs
src/gc-sequence/src/map_result.rs
src/gc-sequence/src/sequence_fn.rs
src/gc-sequence/src/then.rs

Closes #21. @kyren from further inspection I saw the trait bounds causing issues were not added by the proc macro when the `S` param was absent, since `synstructure` doesn't produce `where` clauses for structs/enums when everything is known (no generics). To fix this, I took your suggestion and added a `bound = "<code>"` option to `#[collect]` that overrides the default bounds added by `AddBounds::Fields`.
My original problem just uses the `S` param as a container for type aliases that already implement `Collect`, so using `#[collect(bound = "")]` solves my problem and i can successfully build again.
Also, when I first started using `gc-arena`, I found it a bit hard to get started just because of a lack of detail about how to actually derive `Collect` (since it needs the additional …

add derive bound option

---

src/gc-arena/src/collect_impl.rs
src/gc-arena/tests/ui/bad_collect_bound.stderr

Seems like this type was missing from the existing static collection impls.

Allow chars to be collected

---

src/gc-arena/src/gc.rs
src/gc-arena/src/gc_cell.rs

This adds more useful Debug and Pointer impls for the Gc and GcCell types, and adds a Display impl for the Gc type.  These impls mirror the implementations for Rc and RefCell from the standard library.
Note: this does mean that you will no longer be able to derive Debug on types that contain a Gc ~or GcCell~ if they themselves contain types that don't implement Debug.  You still can manually implement Debug in this case however.

Add more useful Debug, Pointer, and Display impls

---

src/gc-arena/src/arena.rs
src/gc-arena/src/lib.rs

Some slight improvements to the documentation of the `Arena` type:
- Move explanatory paragraphs from `make_arena` to `Arena`;
- Add a `Root<'lt, R>` type alias to simplify signatures;
- Remove useless `#[allow(unused)]` attributes.

Small documentation improvements

---

src/gc-arena/src/collect_impl.rs

These implementations accept arbitrary `S: BuildHasher`, but don't trace the value at all.
This adds an extra `S: 'static` bound to prevent smuggling Gc pointers through the hasher. (All 'real' hashers are `'static`, so this is better than adding a `Collect` bound w.r.t. third-party hashers support)

Fix unsoundness in Hash{Map, Set}'s Collect implementation

---

src/gc-arena/src/context.rs
src/gc-arena/src/dynamic_roots.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/gc_cell.rs
src/gc-arena/src/gc_weak.rs
src/gc-arena/src/gc_weak_cell.rs
src/gc-arena/src/lib.rs
src/gc-arena/src/types.rs
src/gc-arena/src/unsize.rs
src/gc-arena/tests/tests.rs

This rewrites the `GcBox` internals to use a manually-implemented vtable instead of relying on `dyn Collect`, enabling two improvements:
- with `GcBox` now self-contained, the unsizing coercion in `CollectionContext::trace/write_barrier` is no longer necessary, which means that `Gc` pointers can support unsized types;
- similarly, the only place where a `T: Collect` bound is now required is during allocation, this makes removing the bound on `Gc` (like in #22) viable.
This could also allow removing the `Self: Sized` bound on `Collect::needs_trace()`, but this is technically a breaking change (making the trait non-object-safe) so idk if it should be done?
A small wrinkle though: unsized coercions for custom smart pointers aren't possible in stable Rust, so I've added an `unsize!(gc => …

Basic support for `Gc` pointers to unsized types

---

src/gc-arena/src/gc_weak.rs
src/gc-arena/src/gc_weak_cell.rs

These work the same way as the corresponding methods on the strong versions of these types.

Add `ptr_eq` and `as_ptr` to weak types

---

src/gc-arena/src/arena.rs
src/gc-arena/src/context.rs
src/gc-arena/tests/tests.rs

Closes #44. Solves the overflow crash from accumulating `remembered_size` across collect cycles. I'm by no means an expert on this crate, so please check this thoroughly.
It seems like `remembered_size` was meant to be a running total through one collection cycle, but was not being reset to zero at the end of sweeping like `allocation_debt` was. To solve this, I just set it to zero along with `allocation_debt` and use the old value in the calculation of `sleep` for `wakeup_total`.
I've also included a regression test that makes sure that several similar values in `Context` all remain bounded. Unfortunately this required exposing a new public method in `Arena` for getting the value of `remembered_size`. Feel free to make changes if this can be avoided. I would have normally made it …

fix remembered_size acc error

---

src/gc-arena/Cargo.toml
src/gc-arena/src/context.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/gc_weak.rs
src/gc-arena/src/gc_weak_cell.rs
src/gc-arena/src/lib.rs
src/gc-arena/src/types.rs

This PR reduces the size of the GC object metadata from 3 `usize`s to 2 `usize`s. This is achieved in two ways:
- Using pointer tagging to store the GC flags in the low bits of the vtable pointer; to ensure enough bits are available, the `CollectVtable` type is now over-aligned.
- Removing the `traced_weak_ref` flag in favor of a 4th color: `GcColor::WhiteWeak`.

Shrink GC object headers 

---

src/gc-arena/src/gc_weak.rs
src/gc-arena/src/gc_weak_cell.rs

This is mainly intended for implementors of weak data-structures, to allow the cleaning of stale references in `Collect::trace`, where fully upgrading a `GcWeak` isn't possible.
An alternative API would be to expose upgrade methods on `CollectionContext` instead, but this eems much more constraining on the possible space of GC algorithms.

Expose the live GC flag as `GcWeak(Cell)::is_dropped`

---

.circleci/config.yml
src/gc-arena-derive/Cargo.toml
src/gc-arena-derive/src/lib.rs
src/gc-arena/tests/ui/multiple_require_static.stderr
src/gc-arena/tests/ui/no_drop_and_drop_impl.stderr
src/gc-arena/tests/ui/require_static_enum_variant.stderr

Some code simplifications made error messages slightly different.
This also bumps CI's rustc to make the UI test pass.

chore: update `gc-arena-derive` to use `syn` 2

---

src/gc-arena/src/context.rs

On 32-bit targets, `usize::MAX` is `u32::MAX`, which is small enough that we don't lose any precision. This will become relevant once we can run our tests under Miri on wasm32-wasi

Only run test_clamp_f64_precision on 64-bit targest

---

src/gc-arena/src/collect_impl.rs

Replace `impl<T: Collect> Collect for Box<[T]>` with `impl<T: Collect> Collect for [T]`: allows the existing `Box<T: ?Sized + Collect>` impl to work for `Box<[T]>`, as well as the existing `Rc<T: ?Sized + Collect>` impl to work for `Rc<[T]>`, etc.
Also implements `Collect` for some additional `'static` types: `str`, `CStr`, `CString`, `Path`, `PathBuf`, `OsStr`, `OsString`.

Add `Collect` impls for more types.

---

src/gc-arena/src/dynamic_roots.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/lib.rs
src/gc-arena/src/lock.rs
src/gc-arena/tests/tests.rs

A bunch of bells and whistles:
- move the lock types into their separate module, to not clutter the crate root;
- implement *all* the traits;
- add some extra methods (`into_inner`, `get_mut`, `take`);
- replace `Gc::write_(ref_)cell` by `Gc::unlock` and the `Unlock` trait;
- add type aliases for `Gc`+locks combinations.
I wanted to add `OnceLock` too, but I realized that `OnceCell` will only be stabilized in Rust 1.70, so I guess I'll have to wait a little still.

Expand upon `Lock` APIs

---

src/gc-arena/src/arena.rs
src/gc-arena/src/context.rs
src/gc-arena/src/dynamic_roots.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/gc_weak.rs
src/gc-arena/src/lock.rs

Adds `#[inline]` to trivial methods, so that the compile-time wrappers get properly optimized out without having to enable LTO.

Inline trivial methods

---

src/gc-arena/src/gc.rs
src/gc-arena/src/gc_weak.rs
src/gc-arena/src/lock.rs

(also, add `impl AsRef` for `Gc`, and remove extra borrows from other `Gc`-taking methods)
This is sound, as `&'gc T` doesn't implement `Collect` (unless `'gc` ends up being `'static`, which will be impossible once #63 is merged) and so cannot escape the current arena callback by being stored in the GC root.

Add `Gc::as_ref` to get a `&'gc T` from a `Gc<'gc, T>`

---

src/gc-arena/src/arena.rs

Box the `Context` inside `Arena`, so that `map_root` is more efficient, and add some `'gc` lifetimes missed in #66.

Small changes to `Arena`

---

.circleci/config.yml
src/gc-arena/src/barrier.rs
src/gc-arena/src/gc.rs
src/gc-arena/src/lib.rs
src/gc-arena/src/lock.rs
src/gc-arena/tests/tests.rs
src/gc-arena/tests/ui/bad_write_field_projections.rs
src/gc-arena/tests/ui/bad_write_field_projections.stderr

This adds new APIs for safe field-level mutation:
- Add `barrier` module, with `Write`, `field!`, `unlock!`;
- Move `Unlock` into the `barrier` module;
- Rename `Gc::write_barrier` to `Gc::write` and make it return a `&'gc Write<T>`.
See the `field_locks` test for a simple example.

Reified `&Write<T>` barriers and `field!` projections.

---

src/gc-arena/src/arena.rs

The missing `$crate` prefix was preventing `gc_arena::Rootable![Foo<'gc>]` from compiling.
-------
Relatedly, and following our discussion on Discord a few weeks ago, should I change the name of the "default lifetime" of the short form to `'__`, or `'_`? (the latter would be most natural, but would require a proc-macro) This would make the short form usable in most scenarios, when a `'gc` lifetime is already in scope.

Fix `Rootable!` not compiling if not directly imported

---

src/gc-arena-derive/Cargo.toml
src/gc-arena-derive/src/lib.rs
src/gc-arena/src/arena.rs
src/gc-arena/tests/tests.rs

This allows using the short form even when a `'gc` lifetime is already in scope.
For ease of future maintenance, the lifetime substitution is done by a procedural macro instead of a recursive tt-muncher.

Use elided lifetimes instead of `'gc` for the short form of `Rootable!`

---

src/gc-arena/src/dynamic_roots.rs
src/gc-arena/src/lib.rs

- Adds `DynamicRootSet::{contains, try_fetch}`;
- Documents `DynamicRoot{, Set}`;
- Use `unlock!` to remove `RefCell` runtime checks during fetching.

`DynamicRootSet` additions

---

src/gc-arena/src/barrier.rs

This fixes potential UB in `Write`'s casting methods.

Add missing `#[repr(transparent)]` on `Write<_>`

---

src/gc-arena/src/gc.rs

This implements the above traits for `Gc<T>` when `T` implements them. I have tried to model the trait impls after how std implements them for `Rc<T>`. There are probably more traits that could be added here. I didn't look too hard at the impls list for `Rc` and just implemented the few that seemed the most useful.
My use case for this is that I would like to use `Gc<Path>`  as keys in a hashmap.

Implement Eq, PartialEq, Ord, PartialOrd and Hash for Gc<T>

---

src/gc-arena/src/barrier.rs

Some dumb `Write` projection methods I found the need for while hacking on Ruffle; ideally there would be a generic safe destructuring macro supporting enums, but this is much simpler to implement ^^

Add methods to project `Write<Option<_>>` and `Write<Result<_, _>>`

---

src/gc-arena/src/collect_impl.rs

`alloc::sync::Arc` only exists on platforms with atomic pointer-size operations. Our inclusion of `Collect` for `Arc<T>` was unconditional, so this was causing compile errors on platforms that don't have such atomic operations. I just added a cfg so we can keep it on all platforms that allow it.

Fix building on platforms without Arc

---

src/gc-arena/src/static_collect.rs

Just adds a few trait impls to `StaticCollect`:
- `From<T>`
- `AsRef<T>`
- `AsMut<T>`
- `Deref<Target = T>`
- `DerefMut`
- `Borrow<T>`
- `BorrowMut<T>`
Originally I was wanting `Borrow<U> for StaticCollect<T> where T: Borrow<U>` for (efficient) use as the key type in a `BTreeMap`, but this seems to be impossible due to the std blanket implementation of `Borrow<T> for T`. Rust _really_ needs negative trait bounds... or at least a `NotSame<T, U>` trait or something... But I digress lol

add StaticCollect traits

---

src/context.rs
src/dynamic_roots.rs
src/gc.rs

This has some additional drive-by cleanup to make things more
consistent. It adds two methods to `Mutation`, one for backwards write
barriers (previously the only kind) and one for forward write barriers.
Both backwards and forward write barriers are changed to take one or
optionally two pointers: the parent and the adopted child. If both
pointers are given, then the barriers check if the parent is black and
the child is white, and if so, invoke the barrier. The backwards write
barrier will turn the parent gray, and the forwards write barrier will
turn the child gray.
If the backwards write barrier is only given the parent pointer, then it
unconditionally turns it gray if it was black, allowing it to adopt any
pointers at all. If the forwards write barrier is only given the child
pointer, …

Simplest possible forward write barriers.

---

src/gc.rs

I don't see any reason this shouldn't be implemented, so I guess this was just forgotten...

Implement `Borrow<T>` for `Gc<'gc, T>`

---

.circleci/config.yml
Cargo.toml
derive/src/lib.rs
src/allocator_api.rs
src/arena.rs
src/collect.rs
src/collect_impl.rs
src/context.rs
src/dynamic_roots.rs
src/gc.rs
src/gc_weak.rs
src/hashbrown.rs
src/lock.rs
src/static_collect.rs
src/types.rs
tests/tests.rs
tests/ui/bad_collect_bound.stderr
tests/ui/require_static_not_static.rs
tests/ui/require_static_not_static.stderr

Implements (mostly) the changes discussed in https://github.com/kyren/gc-arena/pull/105#issuecomment-2225971064.  
A small difference: I ditched the `CollectFlags` abstraction in favor of keeping a simple boolean; this makes the trait slightly less cumbersome to implement.
This also refactors `Context` to drastically reduce the need for `RefCell` locking, by borrowing the gray queues mutably during marking and tracing.

`Collect` trait breaking changes

---

.circleci/config.yml
Cargo.toml
src/types.rs
tests/ui/bad_collect_bound.stderr

The Strict Provenance APIs are stable since Rust 1.84, so let's use them instead.

Remove `sptr` polyfill for Strict Provenance APIs

---

src/gc.rs
src/lock.rs

The name clash with `std::sync::OnceLock` is a little unfortunate, but I can't think of a better name.

Add `OnceLock` (a GC-aware `OnceCell`)

---

.circleci/config.yml
Cargo.toml
derive/src/lib.rs
src/arena.rs
src/barrier.rs
src/context.rs
src/dynamic_roots.rs
src/gc.rs
src/gc_weak.rs
src/lock.rs
src/static_collect.rs
src/types.rs
src/unsize.rs
tests/tests.rs
tests/ui/bad_write_field_projections.rs
tests/ui/bad_write_field_projections.stderr

The `field!` macro incorrectly allowed projections through references (e.g. `&Write<&Container> -> &Write<Field>`); migrating to edition 2024 fixes this thanks to the tightening of pattern binding mode rules (decl-macro hygiene ensures that the 2024 rules are applied even if the calling crate is <=2024).

Migrate to Edition 2024 and fix `field!` macro.
